### ISSUE TITLE
No coercion operator is defined between types 'System.Int16' and 'System.Boolean'.

### ISSUE THREAD

**Issue by dipongkor** [jasonsturges/mysql-dotnet-core#11]
I am getting following exception while running any kinds of LINQ operation -

`No coercion operator is defined between types 'System.Int16' and 'System.Boolean'.`

**Comment by jasonsturges** [comment]
Is this with MySQL 8?  

There are some compatibility issues with the latest version of MySQL that haven't been addressed.

**Comment by dipongkor** [comment]
Thanks for quick reply. Then which version I should use?

**Comment by jasonsturges** [comment]
Haven't had time to fully investigate these issues, but I presume there are two options:

1. Downgrade your MySQL Server to version 7
2. Use a different MySQL connector provider, like Pomelo instead of Oracle's MySQL Connector

Pomelo
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql

If you go with Pomelo, I believe the update would go something like this to swap out connector's:

Install via Package Manager:

    PM> Install-Package Pomelo.EntityFrameworkCore.MySql -Version 2.1.2

Or, install via executing the following command:

    $ dotnet add package Pomelo.EntityFrameworkCore.MySql --version 2.1.2	

 Or, add the following line to your .csproj `ItemGroup`:

    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="2.1.2" />	

 In your Startup.cs, remove these using statements:	

     // Remove these lines	
    using MySQL.Data.EntityFrameworkCore;	
    using MySQL.Data.EntityFrameworkCore.Extensions;	

 Then, change the casing of `UseMySQL` to `UseMySql`:	

 ```	
// This method gets called by the runtime. Use this method to add services to the container.	
public void ConfigureServices(IServiceCollection services)	
{	
    // Add framework services.	
    services.AddDbContext<ApplicationDbContext>(options =>	
            options.UseMySql(Configuration.GetConnectionString("DefaultConnection")));	
```

**Comment by efrainsteinbach** [comment]
Maybe this is useful to you:

In my case, this seems to be triggered by an incorrect default column type mapping of boolean properties in EF core (with MySql.Data.EntityFrameworkCore from Oracle, not Pomelo). I was able to work around this issue by specifying the column types for each boolean properties, e.g. with attributes:

        [Column(TypeName = "TINYINT(1)")]
        public bool IsEnabled { get; set; }

**Comment by jasonsturges** [comment]
@efrainsteinbach Interesting - thanks, I'll take a look at that.

**Comment by mmapes** [comment]
> 
> 
> Maybe this is useful to you:
> 
> In my case, this seems to be triggered by an incorrect default column type mapping of boolean properties in EF core (with MySql.Data.EntityFrameworkCore from Oracle, not Pomelo). I was able to work around this issue by specifying the column types for each boolean properties, e.g. with attributes:
> 
> ```
>     [Column(TypeName = "TINYINT(1)")]
>     public bool IsEnabled { get; set; }
> ```
> 
> This is of course not an ideal solution.

This worked for me too. Yay!

**Comment by marouaneterai** [comment]
> Maybe this is useful to you:
> 
> In my case, this seems to be triggered by an incorrect default column type mapping of boolean properties in EF core (with MySql.Data.EntityFrameworkCore from Oracle, not Pomelo). I was able to work around this issue by specifying the column types for each boolean properties, e.g. with attributes:
> 
> ```
>     [Column(TypeName = "TINYINT(1)")]
>     public bool IsEnabled { get; set; }
> ```
> This is of course not an ideal solution.

This works when saving data but not when retrieving data, i suggest to use BIT type instead:
`[Column(TypeName = "BIT")]
public bool IsEnabled { get; set; }`

**Comment by beaudamore** [comment]
I am getting the same error, but I have no bool columns anywhere in the database. I get the error regardless, just doing a simple LINQ like this:
`var films = _context.Film.Where(t => t.Title.Contains(viewModel.TitleSearch));`
Plain text search on plain string column.
I can do:
`var films = _context.Film`
just fine though. 

MySql ver 8 (latest as of today), MySql.Data.EntityFrameworkCore 8.0.16, tried Pomelo but it doesn't support the `MySqlGeometry` types o, I cannot use it.

**Comment by CrestApps** [comment]
Although it's not ideal, I tried the following

    [Column(TypeName = "TINYINT(1)")]
    public bool IsEnabled { get; set; }

and also 

    [Column(TypeName = "BIT")]
    public bool IsEnabled { get; set; }

unfortunately, it did not work. I wrote a robust method [here ](https://github.com/aspnet/EntityFrameworkCore/issues/14051#issuecomment-489361074) that would apply `new BoolToZeroOneConverter<short>` during the creation of the context which works when selecting the EntityModel (SELECT * FROM EntityModel) like this `DbSet.ToListAsync()` or even if I filter the records like this `DbSet.Where(x => x.IsValid == true).ToListAsync()`

However, if I only want to select some columns not everything I get the following error `InvalidOperationException: No coercion operator is defined between types 'System.Int16' and 'System.Boolean'.` 

Here is an example of a code that would trigger the error

```
DbSet.Select(x => new GenericModel
{
   Name = x.Name
   IsValid = x.IsValid 
}).ToListAsync();

public class GenericModel
{
   public string Name { get; set; }
   public bool IsValid { get; set; }
}
```

**Comment by jasonsturges** [comment]
This now works with DotNetCore 3.1, and MySQL 8.

Hopefully all issues are now resolved; otherwise, reopen or log a new issue.
