### ISSUE TITLE
NetCore 3.0 prev Issue

### ISSUE THREAD

**Issue by michalss** [jasonsturges/mysql-dotnet-core#17]
Hi,

Im trying to make it work on DotNetCore 3 but it does not work :(..

`Method 'PopulateDebugInfo' in type 'MySql.Data.EntityFrameworkCore.Infraestructure.MySQLOptionsExtension' from assembly 'MySql.Data.EntityFrameworkCore, Version=8.0.16.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d' does not have an implementation.`

**Comment by jasonsturges** [comment]
Hi, thanks for reporting.

Been meaning to do a series of updates to these templates, and I'll be sure to include .NET Core 3 preview on a branch.

**Comment by jasonsturges** [comment]
This now works with DotNetCore 3.1, and MySQL 8.

Hopefully all issues are now resolved.
