### ISSUE TITLE
dotnet ef update Build Failed

### ISSUE THREAD

**Issue by kironet** [jasonsturges/mysql-dotnet-core#2]
Hello,

I have a problem with converting fresh asp.net core 2.0 project(generated template with authentication) from MSLocalDB to MySQL. 

I did everything from "tutorial" https://github.com/jasonsturges/mysql-dotnet-core 
And created _EFMigrationsHistory table.

But when I run dotnet ef update, it's throwing "Build failed".

But if I just run build CTRL + SHIFT + B, build is successful.

**Comment by kironet** [comment]
Whole day tried to solve that and issue was in crashed mysql server...

**Comment by jasonsturges** [comment]
@kironet Hi, that's frustrating - glad you were able to get it resolved.

Hopefully things are smooth moving forward.  Best.
