### ISSUE TITLE
Login not working on Firefox

### ISSUE THREAD

**Issue by dhiraj1mumbai** [jasonsturges/mysql-dotnet-core#5]
Hi, 

I have followed your instructions and set up this project successfully on a local machine. This application is working fine on all other browsers except Firefox. Reproduce steps as below on Firefox Quantam (57.0.4 64-bit):

1. Run the application
2. Click Login
3. Enter user id and password
4. It will redirect to home page but without login that means you will not be able to see your email id on top right corner. also you can't go to manage section

Above steps are successfully working on IE, Edge, Chrome, Safari

Please help.

**Comment by jasonsturges** [comment]
@dhiraj1mumbai Strange, I installed Firefox 57.0.4 (64-bit) and was able to login without issue.

Are you running IIS or Kestrel, and with or without https?  Any plugin like an ad-blocker that's might interfere?

I'll try some additional testing, but this is presumably a problem with Microsoft's ASP.NET template (https://github.com/aspnet/templating).
