### ISSUE TITLE
Conectar aplicação com mysql

### ISSUE THREAD

**Issue by rubensbferraz** [jasonsturges/mysql-dotnet-core#6]
Ola boa tarte, tudo bem, colega eu sou novo em dotnet e estou precisando realizar uma conexão com mysql  se você puder me ajudar, baixe meu projeto e veja se a estrutura está correta, se eu precisarei separar o backend do frontend ou se posso avançar no projeto do jeito que está.. para mim está bom só falta a conexão, eu já instalei a conexão mysql que baixei do site, em qual pasta terei que realizar minha pagina de conexão...

obrigado

meu repositorio "rubensbferraz"

**Comment by jasonsturges** [comment]
Hi, @rubensbferraz, thanks for the note.

If I follow this correctly, you're asking for a code review of one of your repositories.  Unfortunately I haven't much time for that - I'd recommend asking for a review at Stack Exchange.

If you have problems, please feel free to report back.
