### ISSUE TITLE
Detecting Changes in table in order to detect when any changes

### ISSUE THREAD

**Issue by Vijaykumarj** [jasonsturges/mysql-dotnet-core#8]
Receive Notifications when a table record changes between an asp.net web application and an instance of mysql like **SQLDependency in SQL Server.**

thanks in advance

**Comment by bgrainger** [comment]
Duplicate of mysql-net/MySqlConnector#522.

**Comment by jasonsturges** [comment]
This now works with DotNetCore 3.1, and MySQL 8.

Hopefully all issues are now resolved.
